import type { DemoSeedData, MatterMilestoneStatus, DemoMilestoneLog } from '@/lib/demo/types'

export const MILESTONE_LABELS: Record<MatterMilestoneStatus, string> = {
  instruction_received: 'Instruction received',
  aml_checks_started: 'AML checks started',
  aml_checks_complete: 'AML checks complete',
  title_search_started: 'Title search started',
  title_search_complete: 'Title search complete',
  contracts_received: 'Contracts received',
  contracts_signed: 'Contracts signed',
  closing_date_set: 'Closing date confirmed',
  closed: 'Transaction closed',
}

export const MILESTONE_ORDER: MatterMilestoneStatus[] = [
  'instruction_received', 'aml_checks_started', 'aml_checks_complete',
  'title_search_started', 'title_search_complete', 'contracts_received',
  'contracts_signed', 'closing_date_set', 'closed',
]

export const DEMO_MILESTONE_LOGS: DemoMilestoneLog[] = [
  // matter-001 — Cleared to Close (financed residential purchase)
  { id: 'ml-001-1', matter_id: 'matter-001', status: 'instruction_received', label: 'Instruction received', logged_at: '2026-03-04T09:22:00.000Z', note: 'Fully executed FAR/BAR contract received.' },
  { id: 'ml-001-2', matter_id: 'matter-001', status: 'aml_checks_started', label: 'AML checks started', logged_at: '2026-03-04T11:00:00.000Z', note: 'ID verification initiated for buyer and seller.' },
  { id: 'ml-001-3', matter_id: 'matter-001', status: 'aml_checks_complete', label: 'AML checks complete', logged_at: '2026-03-06T14:30:00.000Z', note: 'All parties cleared.' },
  { id: 'ml-001-4', matter_id: 'matter-001', status: 'title_search_started', label: 'Title search started', logged_at: '2026-03-07T09:00:00.000Z', note: 'Title search ordered with Orange County.' },
  { id: 'ml-001-5', matter_id: 'matter-001', status: 'title_search_complete', label: 'Title search complete', logged_at: '2026-03-12T16:45:00.000Z', note: 'Clear title confirmed — no liens or encumbrances.' },
  { id: 'ml-001-6', matter_id: 'matter-001', status: 'contracts_received', label: 'Contracts received', logged_at: '2026-03-15T10:20:00.000Z', note: 'Closing disclosure and ALTA prepared.' },
  { id: 'ml-001-7', matter_id: 'matter-001', status: 'contracts_signed', label: 'Contracts signed', logged_at: '2026-03-20T15:00:00.000Z', note: 'Buyer and seller signed closing documents.' },
  // matter-002 — Scheduled for Closing (cash purchase, entity buyer)
  { id: 'ml-002-1', matter_id: 'matter-002', status: 'instruction_received', label: 'Instruction received', logged_at: '2026-03-01T10:00:00.000Z', note: 'Contract received from buyer agent.' },
  { id: 'ml-002-2', matter_id: 'matter-002', status: 'aml_checks_started', label: 'AML checks started', logged_at: '2026-03-01T14:00:00.000Z', note: 'Entity verification started for Palm Harbor Ventures LLC.' },
  { id: 'ml-002-3', matter_id: 'matter-002', status: 'aml_checks_complete', label: 'AML checks complete', logged_at: '2026-03-05T11:30:00.000Z', note: 'Entity and beneficial owners verified.' },
  { id: 'ml-002-4', matter_id: 'matter-002', status: 'title_search_started', label: 'Title search started', logged_at: '2026-03-06T09:15:00.000Z', note: 'Title search ordered with Sarasota County.' },
  { id: 'ml-002-5', matter_id: 'matter-002', status: 'title_search_complete', label: 'Title search complete', logged_at: '2026-03-13T11:08:00.000Z', note: 'Title commitment issued — clear.' },
  { id: 'ml-002-6', matter_id: 'matter-002', status: 'contracts_received', label: 'Contracts received', logged_at: '2026-03-18T10:00:00.000Z', note: 'Closing package prepared and sent to parties.' },
  { id: 'ml-002-7', matter_id: 'matter-002', status: 'contracts_signed', label: 'Contracts signed', logged_at: '2026-03-22T14:30:00.000Z', note: 'All parties signed — wire transfer pending.' },
  { id: 'ml-002-8', matter_id: 'matter-002', status: 'closing_date_set', label: 'Closing date confirmed', logged_at: '2026-03-23T09:00:00.000Z', note: 'Closing confirmed for March 26 at Sarasota office.' },
]

export const demoSeedData: DemoSeedData = {
  intakeLeads: [
    {
      id: 'intake-lead-seed-001',
      token: 'demo-token-seed-001',
      createdAt: '2026-04-02T10:00:00.000Z',
      fileReference: 'FL-2026-005',
      emailRecipientName: 'Noah Carter',
      emailRecipientEmail: 'noah.carter+demo@example.com',
      emailSubject: 'Intake form — FL-2026-005',
      emailBody: '',
      demoDelivery: 'link_saved',
      intake: {
        clientName: 'Noah Carter',
        clientEmail: 'noah.carter+demo@example.com',
        clientPhone: '(321) 555-0144',
        transactionRole: 'buyer',
        transactionRoleOther: '',
        matterType: 'Cash Residential Purchase',
        propertyAddress: '22 Maple Ave, Winter Park, FL 32789',
        county: 'Orange County',
        targetClosingDate: '2026-05-20',
        notes: '',
      },
      status: 'submitted',
      clientSubmittedAt: '2026-04-03T14:30:00.000Z',
      submittedIntake: {
        clientName: 'Noah Carter',
        clientEmail: 'noah.carter+demo@example.com',
        clientPhone: '(321) 555-0144',
        transactionRole: 'buyer',
        transactionRoleOther: '',
        matterType: 'Cash Residential Purchase',
        propertyAddress: '22 Maple Ave, Winter Park, FL 32789',
        county: 'Orange County',
        targetClosingDate: '2026-05-20',
        notes: '',
      },
      conflict_check_status: 'pending',
      conflict_check_completed_at: null,
      conflict_check_note: null,
    },
    {
      id: 'intake-lead-seed-002',
      token: 'demo-token-seed-002',
      createdAt: '2026-04-08T09:15:00.000Z',
      fileReference: 'FL-2026-006',
      emailRecipientName: 'Noah Carter',
      emailRecipientEmail: 'noah.carter+new@example.com',
      emailSubject: 'Intake form — FL-2026-006',
      emailBody: '',
      demoDelivery: 'link_saved',
      intake: {
        clientName: 'Noah Carter',
        clientEmail: 'noah.carter+new@example.com',
        clientPhone: '(321) 555-0199',
        transactionRole: 'buyer',
        transactionRoleOther: '',
        matterType: 'Financed Residential Purchase',
        propertyAddress: '7 Pine Road, Orlando, FL 32801',
        county: 'Orange County',
        targetClosingDate: '2026-06-01',
        notes: '',
      },
      status: 'pending_client',
      clientSubmittedAt: null,
      submittedIntake: null,
      conflict_check_status: 'pending',
      conflict_check_completed_at: null,
      conflict_check_note: null,
    },
  ],
  fincenCertRequests: [],
  demoFirm: {
    id: 'demo-firm-sunshine-title',
    name: 'Sunshine Title & Closings, P.A.',
    office_location: 'Orlando, FL',
    email: 'intake@sunshinetitle-demo.example',
    phone: '(407) 555-0112',
    website: 'https://sunshinetitle-demo.example',
    is_demo_firm: true,
  },
  staff: [
    {
      id: 'staff-katherine-ruiz',
      full_name: 'Katherine Ruiz, Esq.',
      role: 'Lead Real Estate Attorney',
      email: 'kruiz@sunshinetitle-demo.example',
    },
    {
      id: 'staff-emma-kline',
      full_name: 'Emma Kline',
      role: 'Paralegal / Closer',
      email: 'ekline@sunshinetitle-demo.example',
    },
  ],
  matters: [
    {
      id: 'matter-001',
      file_id: 'FL-2026-001',
      status: 'Cleared to Close',
      deletedAt: null,
      matter_type: 'Financed Residential Purchase',
      portal_token: 'demo-portal-matter-001',
      property: {
        address: '1427 Orange Blossom Dr, Winter Garden, FL 34787',
        county: 'Orange County',
        property_type: 'Single-Family Home',
      },
      buyer: {
        id: 'buyer-001',
        name: 'Noah Carter',
        type: 'individual',
        email: 'noah.carter+demo@example.com',
        phone: '(321) 555-0144',
      },
      seller: {
        id: 'seller-001',
        name: 'Avery Bennett',
        type: 'individual',
        email: 'avery.bennett+demo@example.com',
        phone: '(321) 555-0149',
      },
      transactionType: 'Purchase',
      purchasePrice: 385000,
      financingType: 'Conventional',
      loanNumber: 'LN-2026-88423',
      lenderName: 'SunTrust Mortgage',
      lenderEmail: 'closer@suntrustmtg.com',
      buyerEmail: 'noah.carter+demo@example.com',
      buyerPhone: '(321) 555-0144',
      sellerEmail: 'avery.bennett+demo@example.com',
      sellerPhone: '(407) 555-0198',
      buyerAgent: 'Marcus Rivera',
      listingAgent: 'Diane Holloway',
      assignedAttorney: 'Katherine Ruiz, Esq.',
      assignedParalegal: 'Emma Kline',
      contractDate: '2026-03-04',
      inspectionDeadline: '2026-03-19',
      financingDeadline: '2026-03-21',
      titleCommitmentDeadline: '2026-03-25',
      possessionDate: '2026-03-28',
      fileOpenedDate: '2026-03-04',
      hoaFlag: false,
      referralSource: 'Agent referral — Marcus Rivera',
      specialNotes: '',
      key_dates: {
        effective_date: '2026-03-03',
        inspection_deadline: '2026-03-11',
        loan_approval_deadline: '2026-03-18',
        closing_date: '2026-03-28',
      },
      tasks: [
        { id: 't-001-1', title: 'Receive executed contract', status: 'completed', deletedAt: null },
        { id: 't-001-2', title: 'Open file & send welcome email', status: 'completed', deletedAt: null },
        { id: 't-001-3', title: 'Order title search', status: 'completed', deletedAt: null },
        { id: 't-001-4', title: 'Order municipal lien/search', status: 'completed', deletedAt: null },
        { id: 't-001-5', title: 'Request payoff from seller lender', status: 'in_progress', deletedAt: null },
        { id: 't-001-6', title: 'Prepare Closing Disclosure/ALTA', status: 'in_progress', deletedAt: null },
        { id: 't-001-7', title: 'Schedule signing', status: 'not_started', deletedAt: null },
      ],
      timeline: [
        { id: 'e-001-1', at: '2026-03-04 09:22', note: 'File opened after fully executed FAR/BAR contract.', deletedAt: null },
        { id: 'e-001-2', at: '2026-03-10 15:40', note: 'Inspection period completed; no repair credits requested.', deletedAt: null },
        { id: 'e-001-3', at: '2026-03-22 10:32', note: 'Buyer requested earlier signing slot if lender package arrives.', deletedAt: null },
      ],
    },
    {
      id: 'matter-002',
      file_id: 'FL-2026-002',
      status: 'Scheduled for Closing',
      deletedAt: null,
      matter_type: 'Cash Residential Purchase',
      portal_token: 'demo-portal-matter-002',
      property: {
        address: '88 Gulf View Ct Unit 5B, Sarasota, FL 34236',
        county: 'Sarasota County',
        property_type: 'Condo',
      },
      buyer: {
        id: 'buyer-002',
        name: 'Palm Harbor Ventures LLC',
        type: 'entity',
        email: 'closings+phv-demo@example.com',
        phone: '(941) 555-0162',
      },
      seller: {
        id: 'seller-002',
        name: 'Lena Whitaker',
        type: 'individual',
        email: 'lena.whitaker+demo@example.com',
        phone: '(941) 555-0188',
      },
      transactionType: 'Purchase',
      purchasePrice: 520000,
      financingType: 'Cash',
      loanNumber: '',
      lenderName: '',
      lenderEmail: '',
      buyerEmail: 'closings+phv-demo@example.com',
      buyerPhone: '(941) 555-0162',
      sellerEmail: 'lena.whitaker+demo@example.com',
      sellerPhone: '(941) 555-0231',
      buyerAgent: 'James Okafor',
      listingAgent: 'Sandra Vega',
      assignedAttorney: 'Katherine Ruiz, Esq.',
      assignedParalegal: 'Emma Kline',
      contractDate: '2026-02-28',
      inspectionDeadline: '2026-03-14',
      financingDeadline: '',
      titleCommitmentDeadline: '2026-03-20',
      possessionDate: '2026-03-26',
      fileOpenedDate: '2026-03-01',
      hoaFlag: true,
      referralSource: 'Repeat client',
      specialNotes: 'HOA estoppel requested 3/2 — pending receipt',
      fincen: {
        reportStatus: 'in_progress',
        completedFields: 108,
        reportingParty: {
          firmName: 'Sunshine Title & Closings, P.A.',
          firmAddress: '1800 S Orange Ave, Suite 200, Orlando, FL 32806',
          firmEin: '59-3847201',
          filingAttorney: 'Katherine Ruiz, Esq.',
        },
        propertyInfo: {
          purchaserEntityName: 'Palm Harbor Ventures LLC',
          purchaserEntityType: 'LLC',
          purchaserEin: '83-4471029',
          stateOfFormation: 'Florida',
          paymentMethods: ['Wire Transfer'],
          totalCashAmount: '520000',
        },
        beneficialOwners: [
          {
            id: 'bo-001',
            fullName: 'Marcus T. Delgado',
            dob: '1978-06-14',
            address: '4201 Bayshore Blvd, Tampa, FL 33611',
            citizenship: 'US Citizen',
            tin: '***-**-4421',
            govIdType: "Driver's Licence",
            govIdNumber: 'D123-456-78-910-0',
            govIdIssuer: 'Florida',
            certifiedAt: '2026-03-18T14:22:00.000Z',
          },
        ],
        certRequest: null,
        retentionDeadline: '2031-03-26',
      },
      key_dates: {
        effective_date: '2026-03-12',
        inspection_deadline: '2026-03-16',
        loan_approval_deadline: '2026-03-16',
        closing_date: '2026-03-26',
      },
      tasks: [
        { id: 't-002-1', title: 'Receive executed contract', status: 'completed', deletedAt: null },
        { id: 't-002-2', title: 'Open file & send welcome email', status: 'completed', deletedAt: null },
        { id: 't-002-3', title: 'Order title search', status: 'completed', deletedAt: null },
        { id: 't-002-4', title: 'Obtain HOA/condo estoppel', status: 'completed', deletedAt: null },
        { id: 't-002-5', title: 'Review survey', status: 'in_progress', deletedAt: null },
        { id: 't-002-6', title: 'Schedule signing', status: 'completed', deletedAt: null },
        { id: 't-002-7', title: 'Record deed and mortgage', status: 'not_started', deletedAt: null },
      ],
      timeline: [
        { id: 'e-002-1', at: '2026-03-13 11:08', note: 'Escrow deposited and title commitment sent to buyer counsel.', deletedAt: null },
        { id: 'e-002-2', at: '2026-03-20 13:55', note: 'Condo estoppel received; prorations updated.', deletedAt: null },
      ],
    },
    {
      id: 'matter-003',
      file_id: 'FL-2026-003',
      status: 'Title Search',
      deletedAt: null,
      matter_type: 'Cash Residential Purchase',
      portal_token: 'demo-portal-matter-003',
      property: {
        address: '3109 Cypress Hammock Ln, Tampa, FL 33618',
        county: 'Hillsborough County',
        property_type: 'Single-Family Home',
      },
      buyer: {
        id: 'buyer-003',
        name: 'Mia Delgado',
        type: 'individual',
        email: 'mia.delgado+demo@example.com',
        phone: '(813) 555-0125',
      },
      seller: {
        id: 'seller-003',
        name: 'Riverside Living Trust',
        type: 'entity',
        email: 'trustee+demo@example.com',
        phone: '(813) 555-0173',
      },
      transactionType: 'Purchase',
      purchasePrice: 299000,
      financingType: 'Cash',
      loanNumber: '',
      lenderName: '',
      lenderEmail: '',
      buyerEmail: 'mia.delgado+demo@example.com',
      buyerPhone: '(813) 555-0125',
      sellerEmail: 'trustee@riversideliving.com',
      sellerPhone: '(813) 555-0300',
      buyerAgent: 'Carla Nguyen',
      listingAgent: 'Tom Ostrowski',
      assignedAttorney: 'Katherine Ruiz, Esq.',
      assignedParalegal: 'Emma Kline',
      contractDate: '2026-03-10',
      inspectionDeadline: '2026-03-25',
      financingDeadline: '',
      titleCommitmentDeadline: '2026-04-08',
      possessionDate: '2026-04-15',
      fileOpenedDate: '2026-03-12',
      hoaFlag: false,
      referralSource: 'Agent referral — Carla Nguyen',
      specialNotes: 'Cash purchase by individual buyer — FinCEN threshold not met. Seller is a trust — require trustee certification and trust agreement',
      key_dates: {
        effective_date: '2026-03-21',
        inspection_deadline: '2026-03-28',
        loan_approval_deadline: '2026-04-04',
        closing_date: '2026-04-15',
      },
      tasks: [
        { id: 't-003-1', title: 'Receive executed contract', status: 'completed', deletedAt: null },
        { id: 't-003-2', title: 'Open file & send welcome email', status: 'completed', deletedAt: null },
        { id: 't-003-3', title: 'Order title search', status: 'in_progress', deletedAt: null },
        { id: 't-003-4', title: 'Order municipal lien/search', status: 'not_started', deletedAt: null },
        { id: 't-003-5', title: 'Request payoff from seller lender', status: 'not_started', deletedAt: null },
        { id: 't-003-6', title: 'Prepare Closing Disclosure/ALTA', status: 'not_started', deletedAt: null },
      ],
      timeline: [
        { id: 'e-003-1', at: '2026-03-21 16:20', note: 'Matter opened and intake package sent to all parties.', deletedAt: null },
      ],
    },
    {
      id: 'matter-004',
      file_id: 'FL-2026-004',
      status: 'Closed/Post-Closing',
      deletedAt: null,
      matter_type: 'Financed Purchase - Post-Closing',
      portal_token: 'demo-portal-matter-004',
      property: {
        address: '590 Harbor Lights Blvd, Fort Lauderdale, FL 33301',
        county: 'Broward County',
        property_type: 'Condo',
      },
      buyer: {
        id: 'buyer-004',
        name: 'Olivia Shaw',
        type: 'individual',
        email: 'olivia.shaw+demo@example.com',
        phone: '(954) 555-0155',
      },
      seller: {
        id: 'seller-004',
        name: 'Meridian Coast Holdings LLC',
        type: 'entity',
        email: 'legal+meridian-demo@example.com',
        phone: '(954) 555-0107',
      },
      transactionType: 'Purchase',
      purchasePrice: 875000,
      financingType: 'Conventional',
      loanNumber: 'LN-2026-91055',
      lenderName: 'Wells Fargo Home Mortgage',
      lenderEmail: 'closings@wellsfargomtg.com',
      buyerEmail: 'olivia.shaw+demo@example.com',
      buyerPhone: '(954) 555-0155',
      sellerEmail: 'legal@meridiancoast.com',
      sellerPhone: '(954) 555-0402',
      buyerAgent: 'Priya Kapoor',
      listingAgent: 'Derek Simmons',
      assignedAttorney: 'Katherine Ruiz, Esq.',
      assignedParalegal: 'Emma Kline',
      contractDate: '2026-02-14',
      inspectionDeadline: '2026-03-01',
      financingDeadline: '2026-03-10',
      titleCommitmentDeadline: '2026-03-14',
      possessionDate: '2026-03-19',
      fileOpenedDate: '2026-02-15',
      hoaFlag: true,
      referralSource: 'Attorney referral',
      specialNotes: 'Foreign seller — FIRPTA withholding applies. Confirm TIN.',
      key_dates: {
        effective_date: '2026-02-10',
        inspection_deadline: '2026-02-17',
        loan_approval_deadline: '2026-02-24',
        closing_date: '2026-03-19',
      },
      tasks: [
        { id: 't-004-1', title: 'Receive executed contract', status: 'completed', deletedAt: null },
        { id: 't-004-2', title: 'Open file & send welcome email', status: 'completed', deletedAt: null },
        { id: 't-004-3', title: 'Prepare Closing Disclosure/ALTA', status: 'completed', deletedAt: null },
        { id: 't-004-4', title: 'Schedule signing', status: 'completed', deletedAt: null },
        { id: 't-004-5', title: 'Record deed and mortgage', status: 'completed', deletedAt: null },
        { id: 't-004-6', title: "Issue owner's and lender's policies", status: 'in_progress', deletedAt: null },
      ],
      timeline: [
        { id: 'e-004-1', at: '2026-03-19 17:05', note: 'Closing completed and funds disbursed.', deletedAt: null },
        { id: 'e-004-2', at: '2026-03-21 09:14', note: 'Recorded documents received from county clerk.', deletedAt: null },
      ],
    },
  ],
  clients: [
    {
      id: 'client-001',
      full_name: 'Noah Carter',
      email: 'noah.carter+demo@example.com',
      phone: '(321) 555-0144',
      kyc_status: 'approved',
      type: 'individual',
      linked_matter_ids: ['matter-001'],
      created_at: '2026-03-04',
      deletedAt: null,
    },
    {
      id: 'client-002',
      full_name: 'Palm Harbor Ventures LLC',
      email: 'closings+phv-demo@example.com',
      phone: '(941) 555-0162',
      kyc_status: 'approved',
      type: 'entity',
      linked_matter_ids: ['matter-002'],
      created_at: '2026-03-13',
      deletedAt: null,
    },
    {
      id: 'client-003',
      full_name: 'Mia Delgado',
      email: 'mia.delgado+demo@example.com',
      phone: '(813) 555-0125',
      kyc_status: 'pending',
      type: 'individual',
      linked_matter_ids: ['matter-003'],
      created_at: '2026-03-21',
      deletedAt: null,
    },
    {
      id: 'client-004',
      full_name: 'Olivia Shaw',
      email: 'olivia.shaw+demo@example.com',
      phone: '(954) 555-0155',
      kyc_status: 'approved',
      type: 'individual',
      linked_matter_ids: ['matter-004'],
      created_at: '2026-02-11',
      deletedAt: null,
    },
    {
      id: 'client-005',
      full_name: "Sarah O'Brien",
      email: 's.obrien@lawfirm.ie',
      phone: '(407) 555-0199',
      kyc_status: 'approved',
      type: 'individual',
      linked_matter_ids: ['matter-002'],
      created_at: '2026-03-01',
      deletedAt: null,
    },
  ],
  calendarEvents: [
    {
      id: 'evt-001',
      title: 'Closing - FL-2026-002',
      kind: 'closing',
      date: '2026-03-26T14:00:00',
      matter_id: 'matter-002',
      location: 'Sarasota office - Conference Room A',
      assigned_staff_id: 'staff-emma-kline',
      deletedAt: null,
    },
    {
      id: 'evt-002',
      title: 'Loan approval deadline - FL-2026-001',
      kind: 'deadline',
      date: '2026-03-18T17:00:00',
      matter_id: 'matter-001',
      location: 'Deadline tracking',
      assigned_staff_id: 'staff-katherine-ruiz',
      deletedAt: null,
    },
    {
      id: 'evt-003',
      title: 'Buyer call - FL-2026-003',
      kind: 'client_call',
      date: '2026-03-25T10:30:00',
      matter_id: 'matter-003',
      location: 'Phone / Zoom',
      assigned_staff_id: 'staff-emma-kline',
      deletedAt: null,
    },
    {
      id: 'evt-004',
      title: 'Post-closing policy review - FL-2026-004',
      kind: 'internal',
      date: '2026-03-27T09:00:00',
      matter_id: 'matter-004',
      location: 'Orlando office',
      assigned_staff_id: 'staff-katherine-ruiz',
      deletedAt: null,
    },
  ],
  documents: [
    {
      id: 'doc-001',
      matter_id: 'matter-001',
      name: 'Executed Purchase Contract.pdf',
      category: 'Contract',
      uploaded_at: '2026-03-04T09:35:00',
      uploaded_by_staff_id: 'staff-emma-kline',
      status: 'final',
      deletedAt: null,
    },
    {
      id: 'doc-002',
      matter_id: 'matter-001',
      name: 'Title Commitment - Orange County.pdf',
      category: 'Title',
      uploaded_at: '2026-03-09T15:20:00',
      uploaded_by_staff_id: 'staff-katherine-ruiz',
      status: 'reviewed',
      deletedAt: null,
    },
    {
      id: 'doc-003',
      matter_id: 'matter-002',
      name: 'Condo Estoppel Certificate.pdf',
      category: 'Compliance',
      uploaded_at: '2026-03-20T13:40:00',
      uploaded_by_staff_id: 'staff-emma-kline',
      status: 'reviewed',
      deletedAt: null,
    },
    {
      id: 'doc-004',
      matter_id: 'matter-004',
      name: 'Recorded Deed Copy.pdf',
      category: 'Post-Closing',
      uploaded_at: '2026-03-21T09:20:00',
      uploaded_by_staff_id: 'staff-katherine-ruiz',
      status: 'final',
      deletedAt: null,
    },
  ],
}
