/**
 * Seeded demo dataset and static milestone vocabulary (portal narrative).
 * Aligns with `systemContract.domains` for firm seed, matters, and timeline/milestone story — not a runtime loader for the contract object.
 */
import type { DemoSeedData, MatterMilestoneStatus, DemoMilestoneLog } from '@/lib/demo/types'
import { DEMO_MATTERS } from '@/lib/demo/demoMatters'

export const MILESTONE_LABELS: Record<MatterMilestoneStatus, string> = {
  instruction_received: 'Instruction received',
  aml_checks_started: 'AML checks started',
  aml_checks_complete: 'AML checks complete',
  title_search_started: 'Title search started',
  title_search_complete: 'Title search complete',
  contracts_received: 'Contracts received',
  contracts_signed: 'Contracts signed',
  closing_date_set: 'Closing date confirmed',
  closed: 'Transaction closed',
}

export const MILESTONE_ORDER: MatterMilestoneStatus[] = [
  'instruction_received', 'aml_checks_started', 'aml_checks_complete',
  'title_search_started', 'title_search_complete', 'contracts_received',
  'contracts_signed', 'closing_date_set', 'closed',
]

export const DEMO_MILESTONE_LOGS: DemoMilestoneLog[] = [
  // matter-001 — Cleared to Close (financed residential purchase)
  { id: 'ml-001-1', matter_id: 'matter-001', status: 'instruction_received', label: 'Instruction received', logged_at: '2026-03-04T09:22:00.000Z', note: 'Fully executed FAR/BAR contract received.' },
  { id: 'ml-001-2', matter_id: 'matter-001', status: 'aml_checks_started', label: 'AML checks started', logged_at: '2026-03-04T11:00:00.000Z', note: 'ID verification initiated for buyer and seller.' },
  { id: 'ml-001-3', matter_id: 'matter-001', status: 'aml_checks_complete', label: 'AML checks complete', logged_at: '2026-03-06T14:30:00.000Z', note: 'All parties cleared.' },
  { id: 'ml-001-4', matter_id: 'matter-001', status: 'title_search_started', label: 'Title search started', logged_at: '2026-03-07T09:00:00.000Z', note: 'Title search ordered with Orange County.' },
  { id: 'ml-001-5', matter_id: 'matter-001', status: 'title_search_complete', label: 'Title search complete', logged_at: '2026-03-12T16:45:00.000Z', note: 'Clear title confirmed — no liens or encumbrances.' },
  { id: 'ml-001-6', matter_id: 'matter-001', status: 'contracts_received', label: 'Contracts received', logged_at: '2026-03-15T10:20:00.000Z', note: 'Closing disclosure and ALTA prepared.' },
  { id: 'ml-001-7', matter_id: 'matter-001', status: 'contracts_signed', label: 'Contracts signed', logged_at: '2026-03-20T15:00:00.000Z', note: 'Buyer and seller signed closing documents.' },
  // matter-002 — Scheduled for Closing (cash purchase, entity buyer)
  { id: 'ml-002-1', matter_id: 'matter-002', status: 'instruction_received', label: 'Instruction received', logged_at: '2026-03-01T10:00:00.000Z', note: 'Contract received from buyer agent.' },
  { id: 'ml-002-2', matter_id: 'matter-002', status: 'aml_checks_started', label: 'AML checks started', logged_at: '2026-03-01T14:00:00.000Z', note: 'Entity verification started for Palm Harbor Ventures LLC.' },
  { id: 'ml-002-3', matter_id: 'matter-002', status: 'aml_checks_complete', label: 'AML checks complete', logged_at: '2026-03-05T11:30:00.000Z', note: 'Entity and beneficial owners verified.' },
  { id: 'ml-002-4', matter_id: 'matter-002', status: 'title_search_started', label: 'Title search started', logged_at: '2026-03-06T09:15:00.000Z', note: 'Title search ordered with Sarasota County.' },
  { id: 'ml-002-5', matter_id: 'matter-002', status: 'title_search_complete', label: 'Title search complete', logged_at: '2026-03-13T11:08:00.000Z', note: 'Title commitment issued — clear.' },
  { id: 'ml-002-6', matter_id: 'matter-002', status: 'contracts_received', label: 'Contracts received', logged_at: '2026-03-18T10:00:00.000Z', note: 'Closing package prepared and sent to parties.' },
  { id: 'ml-002-7', matter_id: 'matter-002', status: 'contracts_signed', label: 'Contracts signed', logged_at: '2026-03-22T14:30:00.000Z', note: 'All parties signed — wire transfer pending.' },
  { id: 'ml-002-8', matter_id: 'matter-002', status: 'closing_date_set', label: 'Closing date confirmed', logged_at: '2026-03-23T09:00:00.000Z', note: 'Closing confirmed for March 26 at Sarasota office.' },
]

/** Stable demo intake form tokens (also listed on intake not-found recovery). */
export const DEMO_SEED_INTAKE_TOKENS = {
  submitted: 'demo-token-seed-001',
  pendingClient: 'demo-token-seed-002',
} as const

export const demoSeedData: DemoSeedData = {
  intakeLeads: [
    {
      id: 'intake-lead-seed-001',
      token: DEMO_SEED_INTAKE_TOKENS.submitted,
      createdAt: '2026-04-02T10:00:00.000Z',
      fileReference: 'FL-2026-005',
      emailRecipientName: 'Noah Carter',
      emailRecipientEmail: 'noah.carter+demo@example.com',
      emailSubject: 'Intake form — FL-2026-005',
      emailBody: '',
      demoDelivery: 'link_saved',
      intake: {
        clientName: 'Noah Carter',
        clientEmail: 'noah.carter+demo@example.com',
        clientPhone: '(321) 555-0144',
        transactionRole: 'buyer',
        transactionRoleOther: '',
        matterType: 'Cash Residential Purchase',
        propertyAddress: '22 Maple Ave, Winter Park, FL 32789',
        county: 'Orange County',
        targetClosingDate: '2026-05-20',
        notes: '',
      },
      status: 'submitted',
      clientSubmittedAt: '2026-04-03T14:30:00.000Z',
      submittedIntake: {
        clientName: 'Noah Carter',
        clientEmail: 'noah.carter+demo@example.com',
        clientPhone: '(321) 555-0144',
        transactionRole: 'buyer',
        transactionRoleOther: '',
        matterType: 'Cash Residential Purchase',
        propertyAddress: '22 Maple Ave, Winter Park, FL 32789',
        county: 'Orange County',
        targetClosingDate: '2026-05-20',
        notes: '',
      },
      conflict_check_status: 'pending',
      conflict_check_completed_at: null,
      conflict_check_note: null,
    },
    {
      id: 'intake-lead-seed-002',
      token: DEMO_SEED_INTAKE_TOKENS.pendingClient,
      createdAt: '2026-04-08T09:15:00.000Z',
      fileReference: 'FL-2026-006',
      emailRecipientName: 'Noah Carter',
      emailRecipientEmail: 'noah.carter+new@example.com',
      emailSubject: 'Intake form — FL-2026-006',
      emailBody: '',
      demoDelivery: 'link_saved',
      intake: {
        clientName: 'Noah Carter',
        clientEmail: 'noah.carter+new@example.com',
        clientPhone: '(321) 555-0199',
        transactionRole: 'buyer',
        transactionRoleOther: '',
        matterType: 'Financed Residential Purchase',
        propertyAddress: '7 Pine Road, Orlando, FL 32801',
        county: 'Orange County',
        targetClosingDate: '2026-06-01',
        notes: '',
      },
      status: 'pending_client',
      clientSubmittedAt: null,
      submittedIntake: null,
      conflict_check_status: 'pending',
      conflict_check_completed_at: null,
      conflict_check_note: null,
    },
  ],
  fincenCertRequests: [],
  documentRequests: [
    {
      id: 'docreq-001',
      matter_id: 'matter-001',
      title: 'Buyer government-issued photo ID',
      description: 'Clear color copy of driver’s license or passport for each individual buyer.',
      category: 'Compliance',
      requested_at: '2026-03-05T14:00:00.000Z',
      requested_by_staff_id: 'staff-emma-kline',
      status: 'open',
      fulfilled_document_id: null,
      staff_receipt_acknowledged_at: null,
      staff_receipt_reviewed_by_staff_id: null,
      staff_receipt_reviewed_document_id: null,
      staff_follow_up: { status: 'none' as const, note: '', markedById: null, markedByName: null, markedAt: null },
      lifecycle: { status: 'active' as const, cancelledAt: null, cancelledById: null, cancelledByName: null },
    },
    {
      id: 'docreq-002',
      matter_id: 'matter-001',
      title: 'Executed purchase contract',
      description: 'Fully signed FAR/BAR contract for the closing file.',
      category: 'Contract',
      requested_at: '2026-03-04T10:00:00.000Z',
      requested_by_staff_id: 'staff-emma-kline',
      status: 'fulfilled',
      fulfilled_document_id: 'doc-001',
      // Staff-uploaded fulfillment historically — not in client-upload receipt queue.
      staff_receipt_acknowledged_at: '2026-03-04T11:00:00.000Z',
      staff_receipt_reviewed_by_staff_id: 'staff-emma-kline',
      staff_receipt_reviewed_document_id: 'doc-001',
      staff_follow_up: { status: 'needs_follow_up' as const, note: 'Confirm funds letter matches contract buyer names.', markedById: 'staff-emma-kline', markedByName: 'Emma Kline', markedAt: '2026-03-04T11:30:00.000Z' },
      lifecycle: { status: 'active' as const, cancelledAt: null, cancelledById: null, cancelledByName: null },
    },
    {
      id: 'docreq-003',
      matter_id: 'matter-001',
      title: 'Proof of funds letter',
      description: 'Bank letter or statement showing available cash for closing.',
      category: 'Compliance',
      requested_at: '2026-03-10T09:00:00.000Z',
      requested_by_staff_id: 'staff-emma-kline',
      status: 'fulfilled',
      fulfilled_document_id: 'doc-005',
      staff_receipt_acknowledged_at: null,
      staff_receipt_reviewed_by_staff_id: null,
      staff_receipt_reviewed_document_id: null,
      staff_follow_up: { status: 'none' as const, note: '', markedById: null, markedByName: null, markedAt: null },
      lifecycle: { status: 'active' as const, cancelledAt: null, cancelledById: null, cancelledByName: null },
    },
  ],
  demoFirm: {
    id: 'demo-firm-sunshine-title',
    name: 'Sunshine Title & Closings, P.A.',
    office_location: 'Orlando, FL',
    email: 'intake@sunshinetitle-demo.example',
    phone: '(407) 555-0112',
    website: 'https://sunshinetitle-demo.example',
    is_demo_firm: true,
  },
  staff: [
    {
      id: 'staff-katherine-ruiz',
      full_name: 'Katherine Ruiz, Esq.',
      role: 'Lead Real Estate Attorney',
      email: 'kruiz@sunshinetitle-demo.example',
    },
    {
      id: 'staff-emma-kline',
      full_name: 'Emma Kline',
      role: 'Paralegal / Closer',
      email: 'ekline@sunshinetitle-demo.example',
    },
  ],
  matters: [...DEMO_MATTERS],
  clients: [
    {
      id: 'client-001',
      full_name: 'Noah Carter',
      email: 'noah.carter+demo@example.com',
      phone: '(321) 555-0144',
      kyc_status: 'approved',
      type: 'individual',
      linked_matter_ids: ['matter-001'],
      created_at: '2026-03-04',
      deletedAt: null,
    },
    {
      id: 'client-002',
      full_name: 'Palm Harbor Ventures LLC',
      email: 'closings+phv-demo@example.com',
      phone: '(941) 555-0162',
      kyc_status: 'approved',
      type: 'entity',
      linked_matter_ids: ['matter-002'],
      created_at: '2026-03-13',
      deletedAt: null,
    },
    {
      id: 'client-003',
      full_name: 'Mia Delgado',
      email: 'mia.delgado+demo@example.com',
      phone: '(813) 555-0125',
      kyc_status: 'pending',
      type: 'individual',
      linked_matter_ids: ['matter-003'],
      created_at: '2026-03-21',
      deletedAt: null,
    },
    {
      id: 'client-004',
      full_name: 'Olivia Shaw',
      email: 'olivia.shaw+demo@example.com',
      phone: '(954) 555-0155',
      kyc_status: 'approved',
      type: 'individual',
      linked_matter_ids: ['matter-004'],
      created_at: '2026-02-11',
      deletedAt: null,
    },
    {
      id: 'client-005',
      full_name: "Sarah O'Brien",
      email: 's.obrien@lawfirm.ie',
      phone: '(407) 555-0199',
      kyc_status: 'approved',
      type: 'individual',
      linked_matter_ids: ['matter-002'],
      created_at: '2026-03-01',
      deletedAt: null,
    },
  ],
  calendarEvents: [
    {
      id: 'evt-001',
      title: 'Closing - FL-2026-002',
      kind: 'closing',
      date: '2026-03-26T14:00:00',
      matter_id: 'matter-002',
      location: 'Sarasota office - Conference Room A',
      assigned_staff_id: 'staff-emma-kline',
      deletedAt: null,
    },
    {
      id: 'evt-002',
      title: 'Loan approval deadline - FL-2026-001',
      kind: 'deadline',
      date: '2026-03-18T17:00:00',
      matter_id: 'matter-001',
      location: 'Deadline tracking',
      assigned_staff_id: 'staff-katherine-ruiz',
      deletedAt: null,
    },
    {
      id: 'evt-003',
      title: 'Buyer call - FL-2026-003',
      kind: 'client_call',
      date: '2026-03-25T10:30:00',
      matter_id: 'matter-003',
      location: 'Phone / Zoom',
      assigned_staff_id: 'staff-emma-kline',
      deletedAt: null,
    },
    {
      id: 'evt-004',
      title: 'Post-closing policy review - FL-2026-004',
      kind: 'internal',
      date: '2026-03-27T09:00:00',
      matter_id: 'matter-004',
      location: 'Orlando office',
      assigned_staff_id: 'staff-katherine-ruiz',
      deletedAt: null,
    },
  ],
  documents: [
    {
      id: 'doc-001',
      matter_id: 'matter-001',
      name: 'Executed Purchase Contract.pdf',
      category: 'Contract',
      uploaded_at: '2026-03-04T09:35:00',
      uploaded_by_staff_id: 'staff-emma-kline',
      status: 'final',
      deletedAt: null,
    },
    {
      id: 'doc-002',
      matter_id: 'matter-001',
      name: 'Title Commitment - Orange County.pdf',
      category: 'Title',
      uploaded_at: '2026-03-09T15:20:00',
      uploaded_by_staff_id: 'staff-katherine-ruiz',
      status: 'reviewed',
      deletedAt: null,
    },
    {
      id: 'doc-003',
      matter_id: 'matter-002',
      name: 'Condo Estoppel Certificate.pdf',
      category: 'Compliance',
      uploaded_at: '2026-03-20T13:40:00',
      uploaded_by_staff_id: 'staff-emma-kline',
      status: 'reviewed',
      deletedAt: null,
    },
    {
      id: 'doc-004',
      matter_id: 'matter-004',
      name: 'Recorded Deed Copy.pdf',
      category: 'Post-Closing',
      uploaded_at: '2026-03-21T09:20:00',
      uploaded_by_staff_id: 'staff-katherine-ruiz',
      status: 'final',
      deletedAt: null,
    },
    {
      id: 'doc-005',
      matter_id: 'matter-001',
      name: 'Proof of Funds - Palm Harbor Bank.pdf',
      category: 'Compliance',
      source: 'client_portal',
      uploaded_at: '2026-03-11T16:05:00.000Z',
      uploaded_by_staff_id: 'staff-emma-kline',
      status: 'draft',
      deletedAt: null,
    },
    {
      id: 'doc-006',
      matter_id: 'matter-001',
      name: 'Buyer Photo ID - Unlinked Portal Upload.pdf',
      category: 'Compliance',
      source: 'client_portal',
      uploaded_at: '2026-03-12T15:30:00.000Z',
      uploaded_by_staff_id: 'staff-emma-kline',
      status: 'draft',
      deletedAt: null,
    },
  ],
}
